<?php

use Magento\Framework\Escaper;
use Vipps\Checkout\Block\Adminhtml\Order\View\Tab\EventLog;

/**
 * @var EventLog $block
 * @var Escaper $escaper
 * @var \Vipps\Checkout\Gateway\Data\PaymentEventLog $eventLog
 * @var \Vipps\Checkout\Gateway\Data\PaymentEventLog\Item $item
 */

$block = $this;
if (!$block->canShowTab()) {
    return;
}

try {
    $eventLog = $block->getEventLog();
} catch (\Exception $e) {
    echo '<div>' . $e->getMessage() . '</div>';

    return;
}
?>
<h2><?= $escaper->escapeHtml(__('Vipps Payment Event Log')); ?></h2>
<div>
    <table class="admin__table-primary">
        <tbody>
            <tr>
                <th><?= $escaper->escapeHtml(__('Action')); ?></th>
                <th><?= $escaper->escapeHtml(__('Amount')); ?></th>
                <th><?= $escaper->escapeHtml(__('Psp Reference')); ?></th>
                <th><?= $escaper->escapeHtml(__('Processed At')); ?></th>
                <th><?= $escaper->escapeHtml(__('Is Operation Success')); ?></th>
            </tr>
<?php foreach ($eventLog->getItems() as $item): ?>
            <tr>
                <td><?= $item->getPaymentAction(); ?></td>
                <td><span><?= $item->getAmount()->getValue(); ?> <?= $item->getAmount()->getCurrency(); ?></span></td>
                <td><span><?= $item->getPspReference(); ?></span></td>
                <td><span><?= (new \DateTime($item->getProcessedAt()))->format('d-m-Y H:i:s'); ?></span></td>
                <td><span><?= $item->getSuccess() ? 'true' : 'false'; ?></span></td>
            </tr>
<?php endforeach; ?>
        </tbody>
    </table>
</div>
